### PR TITLE
Bump default report version (fixes #56)

### LINKED ISSUE #56: Change default allure report version to 2.6.0
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] feature request

#### What is the current behavior?
Default report version is 2.0.1 (https://docs.qameta.io/allure/#_maven_6)
`The default Allure version is 2.0.1`

#### What is the expected behavior?
If <reportVerstion> isn't present, by default downloading latest stable version, and this is 2.6.0

Also after needed to update version in documentation.

#### Please tell us about your environment:

- Allure version:        2.6.0
- Test framework:        testng@6.8
- Allure adaptor:        allure-testng@2.6.0
- Generate report using: allure-maven@2.9

### PR DESCRIPTION
**Pull request by baev**

### CODE REVIEW

**Comment by Coder1304** [comment]
@baev Shouldn't you update this file as well? 
`allure-2.0.1.zip` to `allure-2.7.0.zip` in resources?
Without that if someone will use default settings the plugin will fail.
Check this line `AllureCommandline.java:134`

**Comment by baev** [comment]
@Coder1304 yeah, you are right. Need to add integration test for that

**Comment by Coder1304** [comment]
@baev Maybe you know when will be released new version?

**Comment by baev** [comment]
We are going to ship version 2.8.0 of report and java integrations tomorrow. Probably will release allure-maven as well

**Comment by Coder1304** [comment]
Great, thanks.

**Comment by baev** [comment]
https://github.com/allure-framework/allure-maven/pull/65

**Pull request merged**
