### PR TITLE
Update dependency versions

### PR DESCRIPTION
**Pull request by emaks**

### CODE REVIEW

**Comment by emaks** [comment]
are there any updates or problems with this changes?

**Comment by baev** [comment]
@emaks sorry for the delay, missed this one

**Comment by baev** [comment]
@emaks thanks!

**Comment by emaks** [comment]
@baev  Could you make maven release with this changes?

**Comment by baev** [comment]
Summon @eroshenkoam

**Comment by eroshenkoam** [comment]
Ok, I'll do it today

**Comment by emaks** [comment]
@eroshenkoam Is there any problems with release?

**Comment by eroshenkoam** [comment]
@emaks we have problems with 3.5 version of maven-plugins. I can release it with version 3.2 or I need more time (couple days) for problem discovering.

**Comment by eroshenkoam** [comment]
@emaks meet new version)

**Pull request merged**
